-- =====================================================
-- RETAIL DATA MODEL - DIMENSIONAL SCHEMA (STAR SCHEMA)
-- =====================================================
-- Description: Comprehensive retail data model for analytics
-- Platform: Snowflake
-- Model Type: Dimensional (Star Schema with Snowflake optimizations)
-- =====================================================

-- Create Database and Schema
CREATE DATABASE IF NOT EXISTS RETAIL_DB;
USE DATABASE RETAIL_DB;

CREATE SCHEMA IF NOT EXISTS RETAIL_SCHEMA;
USE SCHEMA RETAIL_SCHEMA;

-- =====================================================
-- DIMENSION TABLES
-- =====================================================

-- Dimension: Date (Calendar)
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY INTEGER PRIMARY KEY,
    DATE_ACTUAL DATE NOT NULL,
    DAY_OF_WEEK INTEGER,
    DAY_NAME VARCHAR(10),
    DAY_OF_MONTH INTEGER,
    DAY_OF_YEAR INTEGER,
    WEEK_OF_YEAR INTEGER,
    MONTH_NUMBER INTEGER,
    MONTH_NAME VARCHAR(10),
    MONTH_ABBREV VARCHAR(3),
    QUARTER_NUMBER INTEGER,
    QUARTER_NAME VARCHAR(2),
    YEAR_NUMBER INTEGER,
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN,
    HOLIDAY_NAME VARCHAR(50),
    FISCAL_YEAR INTEGER,
    FISCAL_QUARTER INTEGER,
    FISCAL_PERIOD INTEGER,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Dimension: Time
CREATE OR REPLACE TABLE DIM_TIME (
    TIME_KEY INTEGER PRIMARY KEY,
    TIME_ACTUAL TIME NOT NULL,
    HOUR_24 INTEGER,
    HOUR_12 INTEGER,
    MINUTE INTEGER,
    SECOND INTEGER,
    AM_PM VARCHAR(2),
    TIME_PERIOD VARCHAR(20), -- Morning, Afternoon, Evening, Night
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Dimension: Customer
CREATE OR REPLACE TABLE DIM_CUSTOMER (
    CUSTOMER_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(20),
    CUSTOMER_SEGMENT VARCHAR(50), -- VIP, Premium, Standard, New
    LOYALTY_TIER VARCHAR(50), -- Platinum, Gold, Silver, Bronze
    LOYALTY_POINTS INTEGER DEFAULT 0,
    REGISTRATION_DATE DATE,
    FIRST_PURCHASE_DATE DATE,
    LIFETIME_VALUE DECIMAL(15,2),
    
    -- Address Information
    ADDRESS_LINE1 VARCHAR(255),
    ADDRESS_LINE2 VARCHAR(255),
    CITY VARCHAR(100),
    STATE_PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(100),
    
    -- Marketing Preferences
    EMAIL_OPTED_IN BOOLEAN DEFAULT FALSE,
    SMS_OPTED_IN BOOLEAN DEFAULT FALSE,
    
    -- SCD Type 2 fields
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    
    -- Audit fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Dimension: Product
CREATE OR REPLACE TABLE DIM_PRODUCT (
    PRODUCT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_ID VARCHAR(50) UNIQUE NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_DESCRIPTION TEXT,
    SKU VARCHAR(100) UNIQUE NOT NULL,
    BARCODE VARCHAR(100),
    
    -- Product Hierarchy
    CATEGORY_LEVEL1 VARCHAR(100), -- Department
    CATEGORY_LEVEL2 VARCHAR(100), -- Category
    CATEGORY_LEVEL3 VARCHAR(100), -- Subcategory
    
    -- Product Attributes
    BRAND VARCHAR(100),
    MANUFACTURER VARCHAR(100),
    SIZE VARCHAR(50),
    COLOR VARCHAR(50),
    WEIGHT DECIMAL(10,2),
    WEIGHT_UNIT VARCHAR(10),
    
    -- Pricing
    UNIT_COST DECIMAL(15,2),
    LIST_PRICE DECIMAL(15,2),
    MSRP DECIMAL(15,2),
    
    -- Product Status
    PRODUCT_STATUS VARCHAR(50), -- Active, Discontinued, Seasonal
    IS_TAXABLE BOOLEAN DEFAULT TRUE,
    IS_RETURNABLE BOOLEAN DEFAULT TRUE,
    
    -- SCD Type 2 fields
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    
    -- Audit fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Dimension: Store
CREATE OR REPLACE TABLE DIM_STORE (
    STORE_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    STORE_ID VARCHAR(50) UNIQUE NOT NULL,
    STORE_NAME VARCHAR(255) NOT NULL,
    STORE_NUMBER VARCHAR(20),
    
    -- Store Type
    STORE_TYPE VARCHAR(50), -- Flagship, Standard, Outlet, Pop-up
    STORE_FORMAT VARCHAR(50), -- Mall, Standalone, Strip Center
    STORE_SIZE_SQFT INTEGER,
    
    -- Location Information
    ADDRESS_LINE1 VARCHAR(255),
    ADDRESS_LINE2 VARCHAR(255),
    CITY VARCHAR(100),
    STATE_PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(100),
    LATITUDE DECIMAL(10,6),
    LONGITUDE DECIMAL(10,6),
    
    -- Regional Hierarchy
    REGION VARCHAR(100),
    DISTRICT VARCHAR(100),
    TERRITORY VARCHAR(100),
    
    -- Store Manager
    MANAGER_NAME VARCHAR(255),
    MANAGER_ID VARCHAR(50),
    
    -- Store Details
    OPENING_DATE DATE,
    CLOSING_DATE DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    
    -- SCD Type 2 fields
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    
    -- Audit fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Dimension: Promotion
CREATE OR REPLACE TABLE DIM_PROMOTION (
    PROMOTION_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    PROMOTION_ID VARCHAR(50) UNIQUE NOT NULL,
    PROMOTION_NAME VARCHAR(255) NOT NULL,
    PROMOTION_DESCRIPTION TEXT,
    PROMOTION_TYPE VARCHAR(50), -- Percentage Off, Dollar Off, BOGO, Bundle
    PROMOTION_CATEGORY VARCHAR(50), -- Seasonal, Clearance, New Product, Loyalty
    
    -- Promotion Details
    DISCOUNT_PERCENT DECIMAL(5,2),
    DISCOUNT_AMOUNT DECIMAL(15,2),
    START_DATE DATE,
    END_DATE DATE,
    
    -- Promotion Scope
    IS_STORE_WIDE BOOLEAN DEFAULT FALSE,
    IS_ONLINE_ONLY BOOLEAN DEFAULT FALSE,
    MINIMUM_PURCHASE_AMOUNT DECIMAL(15,2),
    MAXIMUM_DISCOUNT_AMOUNT DECIMAL(15,2),
    
    -- Status
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    
    -- Audit fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Dimension: Payment Method
CREATE OR REPLACE TABLE DIM_PAYMENT_METHOD (
    PAYMENT_METHOD_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    PAYMENT_METHOD_ID VARCHAR(50) UNIQUE NOT NULL,
    PAYMENT_METHOD_NAME VARCHAR(100) NOT NULL,
    PAYMENT_TYPE VARCHAR(50), -- Credit Card, Debit Card, Cash, Gift Card, Digital Wallet
    PAYMENT_PROCESSOR VARCHAR(100),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Dimension: Employee (for sales associate attribution)
CREATE OR REPLACE TABLE DIM_EMPLOYEE (
    EMPLOYEE_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    EMPLOYEE_ID VARCHAR(50) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    
    -- Employment Details
    HIRE_DATE DATE,
    TERMINATION_DATE DATE,
    EMPLOYMENT_STATUS VARCHAR(50), -- Active, Terminated, On Leave
    JOB_TITLE VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    
    -- Store Assignment
    PRIMARY_STORE_KEY INTEGER,
    
    -- Manager
    MANAGER_EMPLOYEE_KEY INTEGER,
    
    -- SCD Type 2 fields
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    
    -- Audit fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Dimension: Supplier/Vendor
CREATE OR REPLACE TABLE DIM_SUPPLIER (
    SUPPLIER_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    SUPPLIER_ID VARCHAR(50) UNIQUE NOT NULL,
    SUPPLIER_NAME VARCHAR(255) NOT NULL,
    SUPPLIER_TYPE VARCHAR(50), -- Manufacturer, Distributor, Wholesaler
    
    -- Contact Information
    CONTACT_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    
    -- Address
    ADDRESS_LINE1 VARCHAR(255),
    ADDRESS_LINE2 VARCHAR(255),
    CITY VARCHAR(100),
    STATE_PROVINCE VARCHAR(100),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(100),
    
    -- Supplier Details
    PAYMENT_TERMS VARCHAR(100),
    LEAD_TIME_DAYS INTEGER,
    MINIMUM_ORDER_QUANTITY INTEGER,
    IS_PREFERRED_SUPPLIER BOOLEAN DEFAULT FALSE,
    SUPPLIER_RATING DECIMAL(3,2), -- 1.00 to 5.00
    
    -- Status
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    
    -- SCD Type 2 fields
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    
    -- Audit fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- =====================================================
-- FACT TABLES
-- =====================================================

-- Fact: Sales Transaction (Transaction Grain)
CREATE OR REPLACE TABLE FACT_SALES (
    SALES_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    
    -- Foreign Keys (Dimension References)
    DATE_KEY INTEGER NOT NULL,
    TIME_KEY INTEGER NOT NULL,
    CUSTOMER_KEY INTEGER,
    PRODUCT_KEY INTEGER NOT NULL,
    STORE_KEY INTEGER NOT NULL,
    PROMOTION_KEY INTEGER,
    PAYMENT_METHOD_KEY INTEGER,
    EMPLOYEE_KEY INTEGER,
    
    -- Degenerate Dimensions (Transaction-level attributes)
    TRANSACTION_ID VARCHAR(100) NOT NULL,
    TRANSACTION_LINE_NUMBER INTEGER NOT NULL,
    RECEIPT_NUMBER VARCHAR(100),
    
    -- Transaction Details
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    
    -- Quantity Measures
    QUANTITY_SOLD INTEGER NOT NULL,
    QUANTITY_RETURNED INTEGER DEFAULT 0,
    
    -- Amount Measures (all in local currency)
    UNIT_PRICE DECIMAL(15,2) NOT NULL,
    UNIT_COST DECIMAL(15,2),
    EXTENDED_PRICE DECIMAL(15,2) NOT NULL, -- Quantity * Unit Price
    DISCOUNT_AMOUNT DECIMAL(15,2) DEFAULT 0,
    TAX_AMOUNT DECIMAL(15,2) DEFAULT 0,
    SHIPPING_AMOUNT DECIMAL(15,2) DEFAULT 0,
    NET_SALES_AMOUNT DECIMAL(15,2) NOT NULL, -- Extended Price - Discount + Tax + Shipping
    
    -- Derived/Calculated Measures
    GROSS_PROFIT_AMOUNT DECIMAL(15,2), -- Net Sales - (Unit Cost * Quantity)
    GROSS_MARGIN_PERCENT DECIMAL(5,2), -- (Gross Profit / Net Sales) * 100
    
    -- Transaction Attributes
    TRANSACTION_TYPE VARCHAR(50), -- Sale, Return, Exchange
    CHANNEL VARCHAR(50), -- In-Store, Online, Mobile, Phone
    ORDER_ID VARCHAR(100), -- For online orders
    
    -- Audit fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    -- Foreign Key Constraints
    FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    FOREIGN KEY (TIME_KEY) REFERENCES DIM_TIME(TIME_KEY),
    FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_KEY),
    FOREIGN KEY (PROMOTION_KEY) REFERENCES DIM_PROMOTION(PROMOTION_KEY),
    FOREIGN KEY (PAYMENT_METHOD_KEY) REFERENCES DIM_PAYMENT_METHOD(PAYMENT_METHOD_KEY),
    FOREIGN KEY (EMPLOYEE_KEY) REFERENCES DIM_EMPLOYEE(EMPLOYEE_KEY)
);

-- Fact: Inventory Snapshot (Daily Snapshot)
CREATE OR REPLACE TABLE FACT_INVENTORY (
    INVENTORY_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    
    -- Foreign Keys
    DATE_KEY INTEGER NOT NULL,
    PRODUCT_KEY INTEGER NOT NULL,
    STORE_KEY INTEGER NOT NULL,
    SUPPLIER_KEY INTEGER,
    
    -- Snapshot Date
    SNAPSHOT_DATE DATE NOT NULL,
    
    -- Inventory Quantities
    BEGINNING_ON_HAND_QUANTITY INTEGER,
    RECEIPTS_QUANTITY INTEGER DEFAULT 0,
    SALES_QUANTITY INTEGER DEFAULT 0,
    RETURNS_QUANTITY INTEGER DEFAULT 0,
    ADJUSTMENTS_QUANTITY INTEGER DEFAULT 0, -- Shrinkage, damage, etc.
    ENDING_ON_HAND_QUANTITY INTEGER,
    
    -- Reorder Information
    REORDER_POINT INTEGER,
    REORDER_QUANTITY INTEGER,
    SAFETY_STOCK_QUANTITY INTEGER,
    
    -- Inventory Valuation
    UNIT_COST DECIMAL(15,2),
    INVENTORY_VALUE DECIMAL(15,2), -- Ending On Hand * Unit Cost
    
    -- Inventory Metrics
    DAYS_OF_SUPPLY INTEGER,
    STOCK_STATUS VARCHAR(50), -- In Stock, Low Stock, Out of Stock, Overstock
    
    -- Audit fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    -- Foreign Key Constraints
    FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_KEY),
    FOREIGN KEY (SUPPLIER_KEY) REFERENCES DIM_SUPPLIER(SUPPLIER_KEY),
    
    -- Ensure one record per day/product/store
    UNIQUE (SNAPSHOT_DATE, PRODUCT_KEY, STORE_KEY)
);

-- Fact: Purchase Orders (Orders from suppliers)
CREATE OR REPLACE TABLE FACT_PURCHASE_ORDER (
    PURCHASE_ORDER_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    
    -- Foreign Keys
    ORDER_DATE_KEY INTEGER NOT NULL,
    EXPECTED_DELIVERY_DATE_KEY INTEGER,
    ACTUAL_DELIVERY_DATE_KEY INTEGER,
    PRODUCT_KEY INTEGER NOT NULL,
    STORE_KEY INTEGER NOT NULL,
    SUPPLIER_KEY INTEGER NOT NULL,
    
    -- Degenerate Dimensions
    PURCHASE_ORDER_NUMBER VARCHAR(100) NOT NULL,
    PURCHASE_ORDER_LINE_NUMBER INTEGER NOT NULL,
    
    -- Order Details
    ORDER_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    EXPECTED_DELIVERY_DATE DATE,
    ACTUAL_DELIVERY_DATE DATE,
    
    -- Quantities
    ORDER_QUANTITY INTEGER NOT NULL,
    RECEIVED_QUANTITY INTEGER DEFAULT 0,
    REJECTED_QUANTITY INTEGER DEFAULT 0,
    
    -- Amounts
    UNIT_COST DECIMAL(15,2) NOT NULL,
    EXTENDED_COST DECIMAL(15,2) NOT NULL, -- Order Quantity * Unit Cost
    SHIPPING_COST DECIMAL(15,2) DEFAULT 0,
    TAX_AMOUNT DECIMAL(15,2) DEFAULT 0,
    TOTAL_COST DECIMAL(15,2) NOT NULL,
    
    -- Order Status
    ORDER_STATUS VARCHAR(50), -- Pending, Approved, Shipped, Received, Cancelled
    
    -- Performance Metrics
    LEAD_TIME_DAYS INTEGER, -- Actual Delivery Date - Order Date
    IS_ON_TIME BOOLEAN,
    IS_COMPLETE BOOLEAN,
    
    -- Audit fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    -- Foreign Key Constraints
    FOREIGN KEY (ORDER_DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_KEY),
    FOREIGN KEY (SUPPLIER_KEY) REFERENCES DIM_SUPPLIER(SUPPLIER_KEY)
);

-- Fact: Customer Interactions (for customer service and engagement tracking)
CREATE OR REPLACE TABLE FACT_CUSTOMER_INTERACTION (
    INTERACTION_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    
    -- Foreign Keys
    DATE_KEY INTEGER NOT NULL,
    TIME_KEY INTEGER NOT NULL,
    CUSTOMER_KEY INTEGER NOT NULL,
    STORE_KEY INTEGER,
    EMPLOYEE_KEY INTEGER,
    
    -- Degenerate Dimensions
    INTERACTION_ID VARCHAR(100) NOT NULL,
    
    -- Interaction Details
    INTERACTION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    INTERACTION_TYPE VARCHAR(50), -- Service Call, Email, Chat, In-Person, Social Media
    INTERACTION_CHANNEL VARCHAR(50), -- Phone, Email, Web, Mobile App, In-Store
    INTERACTION_REASON VARCHAR(100), -- Inquiry, Complaint, Return, Feedback, Support
    
    -- Outcome
    INTERACTION_OUTCOME VARCHAR(100), -- Resolved, Escalated, Pending, Closed
    RESOLUTION_TIME_MINUTES INTEGER,
    
    -- Satisfaction
    CUSTOMER_SATISFACTION_SCORE INTEGER, -- 1-5 rating
    
    -- Text Fields
    INTERACTION_SUMMARY TEXT,
    RESOLUTION_NOTES TEXT,
    
    -- Audit fields
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    -- Foreign Key Constraints
    FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    FOREIGN KEY (TIME_KEY) REFERENCES DIM_TIME(TIME_KEY),
    FOREIGN KEY (CUSTOMER_KEY) REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),
    FOREIGN KEY (STORE_KEY) REFERENCES DIM_STORE(STORE_KEY),
    FOREIGN KEY (EMPLOYEE_KEY) REFERENCES DIM_EMPLOYEE(EMPLOYEE_KEY)
);

-- =====================================================
-- BRIDGE TABLES (Many-to-Many Relationships)
-- =====================================================

-- Bridge: Product-Supplier (products can have multiple suppliers)
CREATE OR REPLACE TABLE BRIDGE_PRODUCT_SUPPLIER (
    PRODUCT_SUPPLIER_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_KEY INTEGER NOT NULL,
    SUPPLIER_KEY INTEGER NOT NULL,
    IS_PRIMARY_SUPPLIER BOOLEAN DEFAULT FALSE,
    UNIT_COST DECIMAL(15,2),
    LEAD_TIME_DAYS INTEGER,
    MINIMUM_ORDER_QUANTITY INTEGER,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRATION_DATE DATE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    FOREIGN KEY (SUPPLIER_KEY) REFERENCES DIM_SUPPLIER(SUPPLIER_KEY),
    
    UNIQUE (PRODUCT_KEY, SUPPLIER_KEY, EFFECTIVE_DATE)
);

-- Bridge: Promotion-Product (promotions can apply to multiple products)
CREATE OR REPLACE TABLE BRIDGE_PROMOTION_PRODUCT (
    PROMOTION_PRODUCT_KEY INTEGER AUTOINCREMENT PRIMARY KEY,
    PROMOTION_KEY INTEGER NOT NULL,
    PRODUCT_KEY INTEGER NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    FOREIGN KEY (PROMOTION_KEY) REFERENCES DIM_PROMOTION(PROMOTION_KEY),
    FOREIGN KEY (PRODUCT_KEY) REFERENCES DIM_PRODUCT(PRODUCT_KEY),
    
    UNIQUE (PROMOTION_KEY, PRODUCT_KEY)
);

-- =====================================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- =====================================================
-- Note: Snowflake automatically manages micro-partitions and clustering
-- These are logical clustering keys for query optimization

ALTER TABLE FACT_SALES CLUSTER BY (DATE_KEY, STORE_KEY);
ALTER TABLE FACT_INVENTORY CLUSTER BY (SNAPSHOT_DATE, STORE_KEY, PRODUCT_KEY);
ALTER TABLE FACT_PURCHASE_ORDER CLUSTER BY (ORDER_DATE_KEY, SUPPLIER_KEY);
ALTER TABLE FACT_CUSTOMER_INTERACTION CLUSTER BY (DATE_KEY, CUSTOMER_KEY);

-- =====================================================
-- COMMENTS FOR DOCUMENTATION
-- =====================================================

COMMENT ON TABLE DIM_DATE IS 'Date dimension with calendar and fiscal attributes';
COMMENT ON TABLE DIM_TIME IS 'Time dimension for intraday analysis';
COMMENT ON TABLE DIM_CUSTOMER IS 'Customer dimension with SCD Type 2 for tracking historical changes';
COMMENT ON TABLE DIM_PRODUCT IS 'Product dimension with hierarchical categories and SCD Type 2';
COMMENT ON TABLE DIM_STORE IS 'Store/location dimension with geographical and organizational hierarchy';
COMMENT ON TABLE DIM_PROMOTION IS 'Promotion/discount dimension';
COMMENT ON TABLE DIM_PAYMENT_METHOD IS 'Payment method dimension';
COMMENT ON TABLE DIM_EMPLOYEE IS 'Employee dimension for sales attribution';
COMMENT ON TABLE DIM_SUPPLIER IS 'Supplier/vendor dimension';
COMMENT ON TABLE FACT_SALES IS 'Sales transaction fact table at line item grain';
COMMENT ON TABLE FACT_INVENTORY IS 'Daily inventory snapshot fact table';
COMMENT ON TABLE FACT_PURCHASE_ORDER IS 'Purchase order fact table for supplier order tracking';
COMMENT ON TABLE FACT_CUSTOMER_INTERACTION IS 'Customer interaction/service fact table';
COMMENT ON TABLE BRIDGE_PRODUCT_SUPPLIER IS 'Many-to-many relationship between products and suppliers';
COMMENT ON TABLE BRIDGE_PROMOTION_PRODUCT IS 'Many-to-many relationship between promotions and products';

-- =====================================================
-- END OF DDL
-- =====================================================



